### ISSUE TITLE
Immediately closes when opening a connection

### ISSUE THREAD

**Issue by adamsar** [HenningM/express-ws#10]
Hello there,

First kudos for this package - makes websockets much less painful in expressjs.

I'm having a bit of trouble making a connect to the socket. I start the server with:

`
app = require('express-ws')(express()).app;
`

then set up the route like so

```
  app.ws('/ws/route', function (ws, req) {
    console.info("connected");
    ws.on('message', function (msg) {
      ws.send(msg);
    })
  });
```

but testing this with 

`
var test = new WebSocket("ws://localhost:3000/ws/route");test.onerror = function () {console.error("error");};test.onclose = function () {console.info("close");};
`

yields "close" in the console. Is there something obvious that I'm doing wrong?

**Comment by kudos** [comment]
I had this problem today, it turned out to be my catchall error handler that I included at the bottom of the `app.use` callback stack after the route declarations. My problem was the signature:

```
app.use(function(req, res, next) {
```

Should have been:

```
app.use(function(err, req, res, next) {
```

**Comment by kudos** [comment]
Actually, that's not quite right. I'm checking for req.upgrade in the 404 handler now.

**Comment by FDIM** [comment]
Was this by any chance happening with iOS device?

**Comment by shreyasseshadri** [comment]
Having the same issue, any fix for this?
