### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by ORESoftware** [HenningM/express-ws#13]
var express = require('express');
var app = express();
var expressWs = require('express-ws')(app);
 
app.use(function (req, res, next) {
  console.log('middleware');
  req.testing = 'testing';
  return next();
});
 
app.get('/', function(req, res, next){
  console.log('get route', req.testing);
  res.end();
});
 
app.ws('/', function(ws, req) {
  ws.on('message', function(msg) {
    console.log(msg);
  });
  console.log('socket', req.testing);
});
 
<h1>server.listen(3000); </h1>

it is not clear to the newb what "server" variable refers to, just FYI

**Comment by HenningM** [comment]
Hi,
Thanks for reporting. Apparently I haven't kept the example in the README file up to date. Should be OK now.

**Comment by ORESoftware** [comment]
cool thanks
