### ISSUE TITLE
include path incorrect in /index.js

### ISSUE THREAD

**Issue by webarchymeta** [HenningM/express-ws#148]
Version: 5.01
The current
```
./src/index
```
points to nowhere in the installed npm package ...

**Comment by jasonolmstead33** [comment]
@webarchymeta @HenningM @OmgImAlexis Ive created a [PR](https://github.com/HenningM/express-ws/pull/149) to revert the changes. seems as though [this](https://github.com/HenningM/express-ws/commit/685e64b58d36318d9111f1b4404f972df7a5a3ff) commit broke loading the /lib folder.

**Comment by OmgImAlexis** [comment]
> @webarchymeta @HenningM @OmgImAlexis Ive created a [PR](https://github.com/HenningM/express-ws/pull/149) to revert the changes. seems as though [this](https://github.com/HenningM/express-ws/commit/685e64b58d36318d9111f1b4404f972df7a5a3ff) commit broke loading the /lib folder. 

Not sure why you opened that PR the revert doesn't need to happen. This is an issue on your end. 

Can you show me the contents of node_modules/express-ws?

**Comment by HenningM** [comment]
I've published a 5.0.2 version without the babel -> esm changes for now. Let me know if this version works better for you, @webarchymeta.

I will have another look at your changes, @OmgImAlexis.

**Comment by jasonolmstead33** [comment]
@HenningM  thank you for that. seems to be working. will close the PR to revert changes.

**Comment by webarchymeta** [comment]
@HenningM  it works for me now
