### ISSUE TITLE
URL with parameter / regex not working

### ISSUE THREAD

**Issue by flashpixx** [HenningM/express-ws#15]
Hello,

I try to create a Websocket URL with

````
po_application.ws('/chat/:did', function( po_socket, po_request ) {
        po_socket.on('message', function( pc_message ) {
            console.log(pc_message);
        });
    });
```

with ```lo_application``` is the express() instance.
The did parameter is defined with
```
po_route.param('did', function(po_request, po_resource, po_next, pc_documentid) {
        pc_request.document = pc_documentid || null;
        po_next();
});
```

Also a URL like ```/chat/(.+)``` is not working. How I can add an URL with a parameter for a Websocket URL

**Comment by bluesmoon** [comment]
I'm also looking for this.  It looks like the `route` is getting coerced into a string, so the fact that it is a regex gets lost.  @HenningM any plans on fixing this?

**Comment by HenningM** [comment]
Hi guys,

First of all: thanks for using this module. Nice to hear some feedback as well and this is a feature I've been planning to implement for a while now, but a bit of external pressure certainly didn't hurt. I've pushed a new version of this module now with a completely different approach to routing. Should make it more similar to the standard express routes.

Unfortunately I haven't been able to test much myself yet, so it would be great if you can have a look at the 1.0.0-rc.1 version. It changes a lot of the inner workings of the library, so this version will probably have a few new bugs, but hopefully I'll be able to iron them out with your assistance. Any feedback will be appreciated.

**Comment by bluesmoon** [comment]
Thanks, awesome turnaround time. Will give it a whirl
