### ISSUE TITLE
works fine in development, fails silently in production (whitelist external origin?)

### ISSUE THREAD

**Issue by jeffalo** [HenningM/express-ws#153]
I'm encountering this bug and I'm not sure what I'm doing wrong.

I am running a express-ws server on localhost:2999, and a sveltekit client on localhost:3000.

When using localhost, this works completely fine.

However, if I tell my sveltekit app to listen on my local IP (eg. 192.168.0.68:3000), my websocket connection goes through and messages to the server get sent fine, but the server doesn't do anything. Nothing happens when a connection/message should be registered. If I try listening to connections through `wsInstance.getWss()`, I see them and I can handle them from there, but I guess that defeats the purpose of using express-ws.

I am encountering this in production too, I think it is because my websocket server and client are on different domains.

I predict this has something to do with it being ran on a different port/domain but I'm lost on what to do? Any ideas? Maybe there's a way to whitelist a domain?

**Comment by jeffalo** [comment]
I figured it out, incase anyone else gets the same issue:

It was the cors module. Make sure to define your ws routes before using cors.

**Comment by trasherdk** [comment]
@jeffalo a short code snippet, demonstrating the solution, would also be helpful :smiley:
