### ISSUE TITLE
getWss(route) returns all wss, but expected only by `route` wss

### ISSUE THREAD

**Issue by breeeew** [HenningM/express-ws#16]
Case from examples:

```javascript
var express = require('express');
var expressWs = require('..')

var expressWs = expressWs(express());
var app = expressWs.app;

app.ws('/a', function(ws, req) {
});
var aWss = expressWs.getWss('/a');

app.ws('/b', function(ws, req) {
});

setInterval(function () {
  aWss.clients.forEach(function (client) {
    client.send('hello');
  });
}, 5000);

app.listen(3000)
```

``aWss.clients`` <-- contains all clients, '/a' and '/b', but expected only '/a' clients.

**Comment by breeeew** [comment]
```javascript
module.exports = function (app, server) {

 ...

  return {
    app: app,
    getWss: function (route) {
      return wsServer; // WAT?
    }
  };
};
```

**Comment by HenningM** [comment]
Hi,

This is an incompatibility from v0 to v1, and one of the main reasons I decided to bump the major version number. Version 1 uses just 1 WebSocketServer to allow the routing to happen in express. This allows the use of dynamic parts in the URL (named parameters & regex).

If you rely on having different WebSocketServers for each route then I would recommend that you stick to v0.2.x.
