### ISSUE TITLE
Error Handling for websocket

### ISSUE THREAD

**Issue by rndmania** [HenningM/express-ws#19]
express provide default error handler and also user add user-defined error handler 
such as below form.
function errorHandler(err, req, res, next) {
}

but, if error is occurred during processing web socket req/res
this error can not handled by  express error handler

so, i wondering that how to handle error for websocket?

**Comment by arik-so** [comment]
Wondering the same.

**Comment by HenningM** [comment]
Hi guys,

Thanks a lot for the feedback. I'm sorry that this library currently doesn't play nicely with the standard error handling in express. Fixing this shouldn't require too much effort, so I'll try to get it done before the end of this week.

**Comment by arik-so** [comment]
Thanks, @HenningM! Any updates? If not, do you have any pointers as to how to get it done? Alas, I have been unsuccessful with domains. But if you can recommend something, I could try to get a PR in.

**Comment by HenningM** [comment]
Hi again @arik-so,

Still haven't found time to implement a fix for this. I haven't dug into the details yet, but I have a feeling that this is related to how middlewares are wrapped here: https://github.com/HenningM/express-ws/blob/master/src/wrap-middleware.js#L1.

**Comment by ncalexan** [comment]
I appear to witness an immediate `Error: socket hang up` when I try to connect to a fresh server using `express-ws`.  I haven't figured out if this is actually `express-ws` or something else.  Will this ticket address catching that type of socket error?  Or is there something else I can do right now?  (I expected `server.on('error', ...)` to address this, but so far no luck.)

**Comment by kraenhansen** [comment]
@HenningM I've created a very simple pull-request that will help if someone accidentally makes a type-o in WS middleware or similar.

**Comment by HenningM** [comment]
The mentioned PR was released with [version 3.0.0](https://github.com/HenningM/express-ws/releases/tag/v3.0.0). Thanks a lot, @kraenhansen!
