### ISSUE TITLE
Broadcasting to a specific room

### ISSUE THREAD

**Issue by morris014** [HenningM/express-ws#20]
app.ws('/send/:chatroom_id', function(ws,req,next) { 
    var chatroom_id = req.chatroom_id;
    var aWss = expressWs.getWss('/send/' + chatroom_id);

    ws.on('message', function(msg) {
         aWss.clients.forEach(function(client) {
            client.send(msg);
         });   
    });
    next();
}); 

How can i implement different chat room by different chatroom_id paramter on the same route

**Comment by HenningM** [comment]
Hi!

I think the best approach here would be to maintain a list of connections for each room. I've included a very simple example to illustrate how this can be done.
```javascript
var chatrooms = {};

app.ws('/chatroom/:name', function(ws, req) {
  var name = req.params.name;
  var room = chatrooms[name] || {
    connections: []
  };
  room.connections.push(ws);
  chatrooms[name] = room;

  ws.on('message', function(msg) {
    room.connections.forEach(function(conn) {
      if (conn === ws) return;
      conn.send(msg);
    });
  });
});
```

**Comment by morris014** [comment]
Yes thank you very much i appreciated it :D

**Comment by morris014** [comment]
var chatrooms = {};

app.ws('/send/:chatroom_id', function(ws,req,next) {
    var chatroom_id = req.chatroom_id;
    var room = chatrooms[chatroom_id] || {
        connections : []
    };
    room.connections.push(ws);
    console.log(room.connections.length);

    var aWss = expressWs.getWss('/send/' + chatroom_id);
    ws.on('message', function(msg) {
        room.connections.forEach(function(conn) {
            conn.send(msg);
        });
    });
    next();
});

I tried this but seems not working

**Comment by morris014** [comment]
Im sorry its working :)

**Comment by morris014** [comment]
Hello can i  ask question .


How can you get session from express ws
