### ISSUE TITLE
Close event for sockets

### ISSUE THREAD

**Issue by AuspeXeu** [HenningM/express-ws#27]
Is there a close event one can react to? For instance to notify other participants in a chat that someone lost the connection?

**Comment by HenningM** [comment]
Hi @AuspeXeu,

Yes, the socket type used in this library is [this one](https://github.com/websockets/ws/blob/master/doc/ws.md#event-close), meaning that you should be able to subscribe to the 'close' event in the same way that you subscribe to 'message' events.

**Comment by AuspeXeu** [comment]
@HenningM works like a charm, thanks a lot!
