### ISSUE TITLE
Looking for https / wss sample ...

### ISSUE THREAD

**Issue by nkolban** [HenningM/express-ws#30]
I am wondering if we have a recipe for setting up a secure (as in https/ssl/tls) express-ws server.  I am trying permutations from googling around but am floundering.   If we had a sample setup for https, that would be fantastic.

**Comment by HenningM** [comment]
Hi,

I've added a simple (but hopefully working) example [here](https://github.com/HenningM/express-ws/blob/master/examples/https.js).

**Comment by nkolban** [comment]
Thank you so much.  That looks like exactly what I was looking for.  Awesome turn around on the request.  Thank you.
