### ISSUE TITLE
Not creating socket

### ISSUE THREAD

**Issue by aarobc** [HenningM/express-ws#39]
I've tried variations on the demo code, even used the exact examples listed in my `app.js`, but it just doesn't seem to be creating the socket. 

to try to keep everything organized I originally broke it out as seen here: https://github.com/aarobc/nodechan/blob/master/src/routes/socket.js

my app.js can be found here: https://github.com/aarobc/nodechan/blob/master/src/app.js#L35

right now I'm just trying to use the basic demo echo code, nothing fancy. Any guidance is appreciated.

**Comment by HenningM** [comment]
Hi @aarobc,

I had a quick look at your code and I think I have an idea of what might be the problem. The `expressWs` function exported by this library requires you to pass it an instance of a `http.Server`, like the one you have [here](https://github.com/aarobc/nodechan/blob/master/src/bin/www#L22). Alternatively you can let the `expressWs` function control the `http.Server` of the express application by not passing it a server. But in this case I'd try passing the server to the function as the second parameter.

To achieve this you could for example expose a app factory function from app.js instead of the app instance itself, thereby allowing injection of the server instance. Let me know if this helps you in any way, otherwise I can help you investigate further.

**Comment by aarobc** [comment]
I apologize for my noobishness, I've attempted to implement it but it's still not working.
Here is what I've tried and still it isn't working:

in `www`:
```
var server = http.createServer(app)
var socket = require('../routes/socket')(app, server)
app.use('/api/scan', socket)
```

in `socket.js`:
```
module.exports = (app, server) => {                        
                                                           
    var expressWS = require('express-ws')(app, server)     
    var express   = require('express')                     
    var router = express.Router()                          
    module.app = app                                       
    router.ws('/', (ws, req) => {                          
        ws.on('message', msg => {                          
            console.log(msg)                               
            ws.send(msg)                                   
        })                                                 
    })                                                     
    return router                                          
}
```

**Comment by aarobc** [comment]
UPDATE: I was able to get it to work by using this workaround, dunno if it's best practice though:
in `www`:
```
var server = http.createServer(app)                  
var socket = require('../routes/socket')(server)
socket.app.use('/api/scan', socket.router)      
```
in `socket.js`:
```
module.exports = (server) => {                        
                                                      
    var express   = require('express')                
    var app       = express()                         
    var expressWS = require('express-ws')(app, server)
    module.router = express.Router()                  
                                                      
    module.app = app                                  
    module.router.ws('/', (ws, req) => {              
        ws.on('message', msg => {                     
            console.log(msg)                          
            ws.send(msg)                              
        })                                            
    })                                                
    return module                                     
}                                                     
```
if this is the "right" way to do it then this can be closed, I just wonder if I'm doing it wrong by creating a new `express()` object.

**Comment by HenningM** [comment]
Hi again @aarobc,

I think this approach should be OK. But creating a new express app shouldn't really be necessary here. You should be able to just pass the one from `app.js` to the function you're exporting from `socket.js`.
