### ISSUE TITLE
What is the API for interacting with a websocket object?

### ISSUE THREAD

**Issue by jameshfisher** [HenningM/express-ws#40]
The documentation only shows an example of `ws.on(...)` and `ws.send(...)`. What else exists? How do I use them?

**Comment by Rush** [comment]
See the ws library. https://github.com/websockets/ws

**Comment by jameshfisher** [comment]
Aha, thanks. It wasn't obvious to me that it just re-exposes the same API. Perhaps the docs could say this and link to it

**Comment by Rush** [comment]
Well, the casual thing to do is to look at `package.json` and if it's not conclusive then just look into the code. Good luck. :-) I'm just trying this library out myself. I looked at the code judging if it's legit, so far it looks fine! (not so humbly speaking the same way I would have written it :D)

**Comment by HenningM** [comment]
Hi @jameshfisher,

Sorry about the lack of pointers in the direction of https://github.com/websockets/ws. Should definitely be added to the README file. Thanks for helping out, @Rush!

**Comment by huyaxiong** [comment]
Thanks @Rush .

**Comment by JC3** [comment]
Ah yeah, I agree, I had zero idea this exposed that API (or really even that that package existed) before I found this!

**Comment by joepie91** [comment]
This was fixed in 1ca841270e207748169b605c2d55d931c5c4b81d and can be closed, I think?
