### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by GeoffreyPlitt** [HenningM/express-ws#41]
I tried the example, I get no connection events, no errors. Something is going wrong and getting swallowed.

Can you publish a working example, complete with client-side code?

**Comment by maxenko** [comment]
Same here...

**Comment by jdtzmn** [comment]
It works for me... it's probably just the example that doesn't work

**Comment by HenningM** [comment]
Hi guys,

Thanks for reporting this. I'll test & update the example later this week. Are you using one of the examples from the examples folder or the one from the README?

**Comment by jdtzmn** [comment]
Not sure which example they were using, but while you are editing the README, I recommend that you add a "socket.on('close')" example, because it took me an annoyingly long amount of time to figure out how to log "socket disconnected" to the console... :laughing:

**Comment by HenningM** [comment]
Thanks for the feedback! I'll make sure to mention that as well. Sorry that you had to figure that one out on your own. The documentation could definitely be improved on many fronts.

**Comment by HenningM** [comment]
I've added a link to the `ws` API documentation in the README.
