### ISSUE TITLE
Any thoughts on how to log handlers globally?

### ISSUE THREAD

**Issue by LeBlaaanc** [HenningM/express-ws#43]
With regular express requests I'm using `bunyan-middleware` any thoughts on how to log ws handlers similarly?

**Comment by roastduck** [comment]
`express-ws` will emit GET request to a fake address when receiving each websocket request (when the connection starts). Can `bunyan-middleware` log those GET requests? I think they contain enough information about each websocket connection. If you need to log every time a socket receives, sends or emits an error, etc., [this PR](https://github.com/HenningM/express-ws/pull/35) may help.

**Comment by LeBlaaanc** [comment]
@roastduck If it's creating a GET request similar to how express does it doesn't seem to log anything.

**Comment by roastduck** [comment]
@LeBlaaanc Does it meet your requirement? Maybe you can close this issue.
