### ISSUE TITLE
Get rid of warning when using Express 5 (alpha.2)

### ISSUE THREAD

**Issue by krzysztof-miemiec** [HenningM/express-ws#44]
I'm using express-ws@2.0.0 with express@5.0.0-alpha.2 successfully. Can we update package.json to get rid of npm warning:
`npm WARN express-ws@2.0.0 requires a peer of express@^4.0.0 but none was installed.`
the only required change:
`"express": "^4.0.0"`
to
`"express": "^4.0.0 || ^5.0.0-alpha.2"`

**Comment by HenningM** [comment]
Should work with [version 3.0.0](https://github.com/HenningM/express-ws/releases/tag/v3.0.0).
