### ISSUE TITLE
Docs do not clearly specify order of router module loading

### ISSUE THREAD

**Issue by jkantr** [HenningM/express-ws#49]
Express generator (and similar) tend to make a habit of loading detached router modules _before_ requiring the app instance (see: https://github.com/expressjs/generator/blob/master/templates/js/app.js) 

The documentation doesn't make clear that the router patching only works if you initialize express-ws *before* require()ing any router-specifying module. @joepie91 said he'd update it :)

**Comment by WesJones127** [comment]
Thank you @jkantr!  This one had me stumped for a while.

**Comment by joepie91** [comment]
Well, that took a bit longer than expected, but I've created PR #60 to address this in the documentation :)

**Comment by HenningM** [comment]
Thanks a lot, @joepie91! Will merge in the PR immediately.

**Comment by joepie91** [comment]
@HenningM: Quick note; the documentation on npmjs.com (which is where most people read it, I suspect) won't be updated until you do a patch release containing the new README - probably a good idea to do that as well :)

**Comment by HenningM** [comment]
Yeah, I know. I'll push an update there later. Thanks for the reminder!
