### ISSUE TITLE
Cannot close sockets

### ISSUE THREAD

**Issue by dangerginger** [HenningM/express-ws#51]
Maybe I am missing something, but I can't see how to close the sockets.  I want my server to respond to `SIGINT` and close gracefully, but the sockets from `app.ws()` and `ws.getInstance().clients` do not have a `.destroy()` method.  If I call `server.close()`, close the browser and wait two minutes then the socket times out and the program will exit.

Any help with this would be appreciated.

**Comment by john-doherty** [comment]
I'm using `ws.terminate()`. I found it in the [WebSocket](https://github.com/websockets/ws/blob/fd910f1460d12bc669afde6ca80a4ba9969e8b99/doc/ws.md#websocketterminate) documentation this module uses.

**Comment by dangerginger** [comment]
Thanks, that did it for me.  My code to close all sockets before exiting is below.  It closes the sockets immediately.

```js
 console.log('tell sockets to close')
 ws.getWss().clients.forEach(socket => {
   console.log('telling socket to close')
   socket.terminate()
 })
```
