### ISSUE TITLE
Does not work when when creating server with http.createServer(app)

### ISSUE THREAD

**Issue by sotirosn** [HenningM/express-ws#6]
this does not work...

```
app = require('express');
require('express-ws')(app);
server = require('http').createServer(app);
server.listen(3000);
```
it only works if you listen from express app directly as in...
```
app = require('express');
require('express-ws')(app);
app.listen(3000);
```
so how then do you allow wss:// from a secure https server?
```
app = require('express');
require('express-ws')(app);
server = require('https').createServer({key:keydata, cert:certdata}, app);
server.listen(3000);
```
The above code runs fine without exceptions but when you try to connect a websocket from the browse you get 'Firefox can't establish a connection to the server at ws://localhost:3000/.'

Also it would be nice if app.ws('route', callback); returned back the instance of app, so that it could be chained as such...

```
app
    .use(....)
    .post(...)
    .ws(...)
    .get(...)
```

**Comment by freebeans** [comment]
I came across this problem recently and found little about it until I realized it only happened when creating the server with http.createServer().

The express-generator does this by default and I use it all the time.

Could you add a note on the README about this?
