### ISSUE TITLE
express-ws = bee's knees

### ISSUE THREAD

**Issue by makeitrein** [HenningM/express-ws#61]
Seriously, was a breeze to incorporate into my current app - many thx for saving me the headache of gluing ws and express together.

**Comment by joepie91** [comment]
Good to hear :)

I'm considering writing a more in-depth article about building abstractions like this, for an educational site I'm working on. If @HenningM is okay with it, it might be an idea to add a link to that article to the README once it's done.

**Comment by HenningM** [comment]
I'm glad to hear that it's useful to you, @makeitrein! We will do our best to improve on the documentation.  @joepie91 has already made some significant efforts on that front. I really appreciate those efforts and I would welcome any further contributions. Linking to your article from the README would be 100% OK by me. Just send me a PR.
