### ISSUE TITLE
Full stack example?

### ISSUE THREAD

**Issue by danosaure** [HenningM/express-ws#62]
Hi,

This might sound like noob-ist request, but being very experienced with express and REST, i'm trying to figure out from the documentation how would the client-side communication would be. If there is a repo that actually show a full stack usage, please let me know.

My goal would be to "translate" the REST call into websocket:

```
POST /users/123
{ pay: 'load' }
```
to something like:

```
ws = new WebSocket("/ws");
....on('click', () => {
  ws.send({method: 'POST', path: '/users/123', data: {pay:'load'}});
});
```

Would this mean that I need to define:

```
router.ws('/users/:id', (ws, req) => {
  ws.send({status: 200, body: {ret:'urn'});
});
```

**Comment by joepie91** [comment]
It sounds like you're trying to wholesale *replace* HTTP requests with a WebSocket, and this isn't generally a good idea.

HTTP is designed specifically for request/response patterns, and is a well-tested solution for that with good browser support. WebSockets are an additional feature on top of HTTP for facilitating bidirectional communication that *doesn't* fit a request/response pattern (eg. publish/subscribe), but isn't meant to replace HTTP for the request/response scenarios.

In other words: you should only use WebSockets for scenarios where you *can't* reasonably express actions in a request/response pattern using HTTP. For all the request/response operations (which are most operations in a typical web application), just use standard HTTP requests/responses.

An example of this might be a hypothetical social network, with the following features:

* __Register / login to user account__
* __Post status update__
* __Add friend__
* __Dashboard that shows the latest posts from friends__
* __Automatically show new posts on the dashboard as they are posted__

You'd divide the responsibilities like this:

* __Register / login to user account:__ HTTP request *(request/response)*
* __Post status update:__ HTTP request *(request/response)*
* __Add friend:__ HTTP request *(request/response)*
* __Dashboard that shows the latest posts from friends:__ HTTP request *(request/response)*
* __Automatically show new posts on the dashboard as they are posted:__ WebSocket *(publish/subscribe)*

**Comment by danosaure** [comment]
Thank you for the extensive explanation. I understand that client->server communication still can be done through the HTTP request, and I could only reserve server->client async updates to the websocket. I've done that in the past.

I'm just wondering what is the `router.ws(routePath)` really for. Does this adds any conversion of the message, or does it only give me one endpoint to create the websocket starting point?

**Comment by joepie91** [comment]
You can specify multiple WebSocket routes for different purposes, or even for multiple resources - for example, if you want to subscribe to updates for a *specific user*, you could have `app.ws("/user/:id", ...)` and only serve updates for that specific user on the socket.

There are some performance caveats to this (often it'll be more efficient to combine messages on a single socket, even for multiple purposes), but there are usecases where having many WebSocket endpoints makes sense.

For *most* applications, though, you'd likely just have a single WebSocket endpoint, defined on a single app or router, optionally with some kind of 'subscribe' mechanism. The purpose of `router.ws` is really just to bring `.ws` closer to feature parity with `.get`.

**Comment by danosaure** [comment]
It doesn't anything on the client-side, but allows a more friendly server-side setup. Now I understand better. I was trying to figure out if it would be a potential replacement for REST calls, but it seems not.

A sample implementation project would have made all this clear and allow us to play with it without needing to setup everything client-side to see if it works or not.

But again, thanks for the explanation.

**Comment by joepie91** [comment]
> It doesn't anything on the client-side, but allows a more friendly server-side setup. Now I understand better. I was trying to figure out if it would be a potential replacement for REST calls, but it seems not.

That's correct.

> A sample implementation project would have made all this clear and allow us to play with it without needing to setup everything client-side to see if it works or not.

The problem with sample projects (in Node.js) is that most modules only have a single narrow purpose, and you're expected to combine it with other modules and your own code to implement a real-world application - and the exact things you combine it with will vary by project. A single module in isolation isn't really meaningful.

Because of that, it's often more practical to explain the concepts *behind* something, in such a way that it's easy for the reader to understand exactly how it fits into what they already have. Hence the extensive explanation above :)
