### ISSUE TITLE
Doesnt work with https

### ISSUE THREAD

**Issue by Dhana-Krishnasamy** [HenningM/express-ws#67]
I have a small app hosted on https as mentioned here http://stackoverflow.com/a/11745114/2147987
express-ws works on ws:// endpoint but not on wss://.  Does express-ws work on ssl?

**Comment by Dhana-Krishnasamy** [comment]
Figured it out...Just pass https server instance as  a second param like shown below

var httpsServer = https.createServer(credentials, app);
httpsServer.listen(8443);
var expressWss = require('express-ws')(app, httpsServer);

On client side:
var wsUrl = 'wss://abc.com/

**Comment by Dhana-Krishnasamy** [comment]
Figured it out...Just pass https server instance as  a second param like shown below

var httpsServer = https.createServer(credentials, app);
httpsServer.listen(8443);
var expressWss = require('express-ws')(app, httpsServer);

On client side:
var wsUrl = 'wss://abc.com/

**Comment by Native-Coder** [comment]
Why does my project structure look so different from these examples? The project that mine generated has an app.js file in the root directory and a /bin/www file where the https server gets defined. If I am defining my https server in a different file from app then how do pass the http server to express-ws?
