### ISSUE TITLE
can't access wss object

### ISSUE THREAD

**Issue by zh99998** [HenningM/express-ws#7]
need to access wss object sometimes, such as get all clients and broadcasting, like this:
https://github.com/einaros/ws#server-sending-broadcast-data

**Comment by HenningM** [comment]
Your use case should be possible in v0.2.4.

See [example/broadcast.js](https://github.com/HenningM/express-ws/blob/master/examples/broadcast.js)

**Comment by aaronrogers** [comment]
How is this supposed to work with `getWss` doesn't take a parameter?  It appears to get a server for all routes and not just the one.
