### ISSUE TITLE
Support Async/Await

### ISSUE THREAD

**Issue by robgev** [HenningM/express-ws#71]
I am trying to use this lib with async/await calls to db but it gives an error: 

```
await dbtest.all('select * from task where assigned_worker = $wrk',
      ^^^^^^
SyntaxError: Unexpected identifier
```

Deleting awaits and asyncs fixes the error.

**Comment by joepie91** [comment]
Can you provide a full snippet of the code that this error occurs in?

**Comment by robgev** [comment]
Actually I fixed this one, thank you

**Comment by cabefrancou** [comment]
I have this one too, what is the solution?
