### ISSUE TITLE
Can I send custom events

### ISSUE THREAD

**Issue by houkk** [HenningM/express-ws#81]
Is it possible to send custom events?

For example, can I listen on 'custom event' in client

**Comment by freebeans** [comment]
You can send any data through the web socket, but you can't send custom events from the server to the client without some abstraction layer between the applications.

If you really need to do this, you can send some data from the server and capture that with this layer before relaying to you application. This way you can fire any custom events you want.

**Comment by houkk** [comment]
Wow, two years ago! 
This is a pretty good solution, I will try it, thank you.
