### ISSUE TITLE
Use the latest `ws`?

### ISSUE THREAD

**Issue by danfuzz** [HenningM/express-ws#90]
It looks like `ws` is two major revs ahead of what `express-ws` lists in its `dependencies`. Perhaps worth moving to it?

**Comment by danfuzz** [comment]
@AuspeXeu: I didn't. From the `ws` changelog <https://github.com/websockets/ws/releases/tag/4.0.0>, it looked like there were enough breaking changes that it wouldn't be trivial for someone like me who isn't familiar with the code (of any of `express-ws`, `express`, _or_ `ws`) to make headway and be confident of a good result.

I just happened to notice the datedness of the dependency when I was tracking down an issue in my own code (which I thought _might_ have been coming from `express-ws` but in the end wasn't). Rather than silently noting it and moving on, I figured I could at least raise the issue here.

Cheers!

**Comment by AuspeXeu** [comment]
That is also how I ended up here haha

**Comment by danfuzz** [comment]
Huh, perhaps the dependency on `ws` from this module would be more profitably expressed under `peerDependencies` instead of plain old `dependencies`.

**Comment by AuspeXeu** [comment]
@danfuzz I think I am switching to the bare `ws` module using this example.

https://github.com/websockets/ws#expressjs-example

**Comment by theflyingape** [comment]
express-ws fails an `npm audit` referring to this DoS vulnerability: https://nodesecurity.io/advisories/550

**Comment by pixelspark** [comment]
Ran into the audit warning as well. Any progress?

**Comment by danfuzz** [comment]
As with @AuspeXeu I've now just dropped my use of this module. In case it helps, here's the commit in my project that made the change: <https://github.com/danfuzz/bayou/pull/466/commits/4ed5569049c138e0e26fb55b1c069e2be8c0a1a6>

**Comment by pixelspark** [comment]
Ah that is easier than I thought. Thanks for the pointer, will use this (perhaps a notice in express-ws's README would be a good idea?)

**Comment by danfuzz** [comment]
BTW, one thing to watch out for is that my change makes it so that `express` isn't involved at all in websocket requests. This means that any route intercepters / middleware you might have installed — notably logging — won't get invoked.

**Comment by theflyingape** [comment]
Same [here](https://github.com/theflyingape/dankdomain/blob/d6315e6a532565fd3a1982d0470f45fe0906b7cc/src/door/app.ts#L33), still using Express for REST APIs, but replaced express-ws using only ws 'upgrade' endpoints to handle the socket connections, without adding more URL paths (because this runs behind Apache proxy), sigh.
